name: Visual Regression Testing

on:
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened ]

jobs:
  reg-screenshot-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      actions: read
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper

      - name: Workaround for detached HEAD
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git checkout ${GITHUB_HEAD_REF#refs/heads/} || git checkout -b ${GITHUB_HEAD_REF#refs/heads/} && git pull origin ${GITHUB_HEAD_REF#refs/heads/}

      - name: verify test
        run: |
          ./gradlew recordRoborazziDebug --stacktrace

      - name: run reg-suit
        run: |
          yarn run reg-suit sync-expected && yarn run reg-suit compare && yarn run reg-suit publish -n

      - name: upload test results to github page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .reg
          destination_dir: ${{ github.head_ref  }}

      - name: find comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]
          body-includes: reg-suit report  # A string to search for in the body of comments.

      - name: upsert comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            reg-suit report
            https://dao0203.github.io/todo-sample-app/${{ github.head_ref }}
          edit-mode: replace
